from datetime import datetime, timezone

applications = [
    {
        "id": 1,
        "company": "Acme Technologies",
        "role": "Junior Backend Developer",
        "status": "applied",
        "job_url": "https://careers.example.com/jobs/101",
        "notes": "Applied through the company website.",
        "applied_at": datetime(2026, 8, 1, 10, 30, tzinfo=timezone.utc),
        "created_at": datetime(2026, 8, 1, 10, 30, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 8, 1, 10, 30, tzinfo=timezone.utc),
    },
    {
        "id": 2,
        "company": "Northstar Labs",
        "role": "Python Developer Intern",
        "status": "interview",
        "job_url": "https://careers.example.com/jobs/102",
        "notes": "Technical interview scheduled for August 25.",
        "applied_at": datetime(2026, 8, 3, 14, 15, tzinfo=timezone.utc),
        "created_at": datetime(2026, 8, 3, 14, 15, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 8, 18, 9, 0, tzinfo=timezone.utc),
    },
    {
        "id": 3,
        "company": "PixelForge",
        "role": "Software Engineering Intern",
        "status": "saved",
        "job_url": "https://careers.example.com/jobs/103",
        "notes": "Update résumé before applying.",
        "applied_at": None,
        "created_at": datetime(2026, 8, 5, 8, 45, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 8, 5, 8, 45, tzinfo=timezone.utc),
    },
    {
        "id": 4,
        "company": "BlueRiver Systems",
        "role": "Graduate Software Engineer",
        "status": "rejected",
        "job_url": "https://careers.example.com/jobs/104",
        "notes": "Rejected after the initial screening.",
        "applied_at": datetime(2026, 7, 20, 11, 0, tzinfo=timezone.utc),
        "created_at": datetime(2026, 7, 20, 11, 0, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 8, 2, 16, 20, tzinfo=timezone.utc),
    },
    {
        "id": 5,
        "company": "Orbit Analytics",
        "role": "Junior API Developer",
        "status": "offer",
        "job_url": "https://careers.example.com/jobs/105",
        "notes": "Offer received; response required by August 28.",
        "applied_at": datetime(2026, 7, 15, 13, 40, tzinfo=timezone.utc),
        "created_at": datetime(2026, 7, 15, 13, 40, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 8, 20, 15, 10, tzinfo=timezone.utc),
    },
    {
        "id": 6,
        "company": "Greenfield Software",
        "role": "FastAPI Backend Intern",
        "status": "applied",
        "job_url": "https://careers.example.com/jobs/106",
        "notes": "",
        "applied_at": datetime(2026, 8, 12, 17, 25, tzinfo=timezone.utc),
        "created_at": datetime(2026, 8, 12, 17, 25, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 8, 12, 17, 25, tzinfo=timezone.utc),
    },
]